name: Deploy

on:
  push:
    branches: [ "deploy-scripts" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Common dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install newman
        run: npm install -g newman

      - name: Get IP address
        id: get_ip
        run: echo "ip_address=$(hostname -I | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      # Species
      ## Dependencies specific to the service Species
      - name: Install Express.js
        run: npm install express

      ## Run integration tests
      - name: Run Tests for Species
        run: species/integration-tests/run.sh

      ## Deployment
      - name: Deploy Changes
        if: success()
        run: |
          sudo netstat -tlnp | grep ':3000' | wc -l
          if [ $? -eq 0 ]; then
            pid=$(sudo lsof -t -i:3000)
            sudo kill $pid
            if [ $? -eq 0 ]; then
              echo "Previous instance killed"
            else
              echo "Error when trying to kill the instance"
            fi
          else
            echo "No running instance to kill"
          fi
          RUNNER_TRACKING_ID="github_01" &&node species/server.js &

      # Animals
      ## Dependencies specific to the service Animals
      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"

      - name: Install Slim
        run: composer require slim/slim:^4.0 slim/psr7:^1.5 --working-dir animals

      ## Integration tests
      - name: Run Tests for Animals
        run: animals/integration-tests/run.sh

      ## Deployment
      - name: Deploy Changes
        if: success()
        run: |
          sudo netstat -tlnp | grep ':4000' | wc -l
          if [ $? -eq 0 ]; then
            pid=$(sudo lsof -t -i:4000)
            sudo kill $pid
            if [ $? -eq 0 ]; then
              echo "Previous instance killed"
            else
              echo "Error when trying to kill the instance"
            fi
          else
            echo "No running instance to kill"
          fi
          RUNNER_TRACKING_ID="github_02" && php -S localhost:4000 -t animals/public &

      # Pictures
      ## Dependencies specific to the service Pictures
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '>=1.17.0'
          check-latest: true

      - name: Install Go libraries
        run: cd pictures && go mod tidy

      - name: Build
        run: |
          cd pictures
          go build .

      ## Integration tests
      - name: Run Tests for Pictures
        run: pictures/integration-tests/run.sh

      ## Deployment
      - name: Deploy Changes
        if: success()
        run: |
          IP_ADDRESS="${{ steps.get_ip.outputs.ip_address }}"
          sudo netstat -tlnp | grep ':5000' | wc -l
          if [ $? -eq 0 ]; then
            pid=$(sudo lsof -t -i:5000)
            sudo kill $pid
            if [ $? -eq 0 ]; then
              echo "Previous instance killed"
            else
              echo "Error when trying to kill the instance"
            fi
          else
            echo "No running instance to kill"
          fi
          cd pictures || exit
          RUNNER_TRACKING_ID="github_03" && go run . $IP_ADDRESS:5000 &