name: Pictures

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Deploy service pictures'
        required: true
        default: 'pictures'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Cache go modules
        id: cache-go
        uses: actions/cache@v3
        env:
          cache-name: cache-go-modules
        with:
          path: ~/go
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install newman
        run: npm install -g newman

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '>=1.17.0'
          check-latest: true
          cache-dependency-path: |
            pictures/go.sum

      - name: Install Go libraries
        run: cd pictures && go mod tidy

      - name: Get IP address
        id: get_ip
        run: echo "::set-output name=ip_address::$(hostname -I | cut -d' ' -f1)"

      - name: Build
        run: |
          cd pictures
          go build .

      - name: Run Tests
        run: pictures/integration-tests/run.sh

      - name: Deploy Changes
        if: success()
        run: |
          IP_ADDRESS="${{ steps.get_ip.outputs.ip_address }}"
          cd pictures
          pkill -f "go run . $IP_ADDRESS:5000" || true
          RUNNER_TRACKING_ID="" && go run . $IP_ADDRESS:5000 &