name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Express.js
        run: npm install express

      - name: Kill API
        if: github.ref == 'refs/heads/main'
        run: pkill -f "node species/server.js" || true

      - name: Start API
        run: RUNNER_TRACKING_ID="" && node species/server.js &
