name: Deploy

on:
  push:
    branches: [ "farmers" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Get IP address
        id: get_ip
        run: echo "ip_address=$(hostname -I | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      # Farmers
      ## Begin Dependencies part
      - name: Setup up python environment
        uses: actions/setup-python@v5
        with:
          python-version: ''

      - name: Install dependencies
        run: |
          cd farmers
          pip install -r requirements.txt
      ## End Dependencies part

      - name: Stop previous service farmers
        if: success()
        run: |
          has_process=$(sudo netstat -tlnp | grep ':6000' | wc -l)
          if [ $has_process -ne 0 ]; then
            pid=$(sudo lsof -t -i:6000)
            sudo kill $pid
          else
            echo "No running instance to kill"
          fi

      - name: Start new service farmers
        run: |
          IP_ADDRESS="${{ steps.get_ip.outputs.ip_address }}"
          RUNNER_TRACKING_ID="github_04" && cd farmers || exit && python main.py --host=$IP_ADDRESS --port=6000 &
